name: Container

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 1 * *'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        run: |
          git clone http://charlesst.us.to:1511/git/root/obsidian.git
          mv obsidian/* .
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Build 9
        run: |
          podman build -t ghcr.io/charles8191/obsidian/9 .
      - name: Push
        run: |
          podman push ghcr.io/charles8191/obsidian/9
