name: ISO

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 3,6,9,12 *'
    
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        run: |
          git clone https://git.almalinux.org/charles2/obsidian.git
          mv obsidian/* .
      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Prepare
        run: mkdir output
      - name: Build 9
        run: |
          sudo podman build -t localhost/9 iso/9
          sudo podman run --privileged -v "$(pwd)/output":/output localhost/9
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.date }}
          name: Build on ${{ steps.date.outputs.date }}
          files: |
            output/*.iso
